### ISSUE TITLE
parseInt base 16

### ISSUE THREAD

**Issue by aerogelio** [stefano/pyduktape#2]
I am testing py_mini_racer(V8) and pyduktape(duktape).

When i parse string to number base 16 passes the following:
    V8:
        n = parsetInt( '09', 16 ); #output = 9
    duktape:
        n = parseInt('09', 16); #output = 0

I am decrypting and this changes the result.
I don't know it is part duktape or pyduktape, greetings.

**Comment by stefano** [comment]
Hi, sorry for the late response, but I didn't receive a notification for the issue. It appears to be a bug in duktape itself. I updated to duktape 1.6, where the bug is resolved. There is now a new version on pipy (0.0.4) which will work as expected.
