### ISSUE TITLE
When I try install, I get this error, I had to install the previous version(0.0.3)

### ISSUE THREAD

**Issue by aerogelio** [stefano/pyduktape#3]
![untitled](https://cloud.githubusercontent.com/assets/2359000/21827010/fc5d78d6-d746-11e6-9bad-c297fd1e5e07.png)

**Comment by stefano** [comment]
It looks like the duktape version I upgraded to has a compilation error on windows (it directly uses uint8_t, which is not supported, instead of duk_uint8_t). I'll look into upgrading to a newer version (if one that fixes the issue is available).

**Comment by stefano** [comment]
I uploaded a new version (0.0.5). Unfortunately I can't test on windows right now, but it should work. Could you please try and report back if it works? Thanks.

**Comment by aerogelio** [comment]
I can already install the new version from the code and pip,  I have not tried it with my application but if something happens I'll let you know, thank you very much. Fantastic plugin.
