### ISSUE TITLE
License clarification and (eventual) re-licensing

### ISSUE THREAD

**Issue by mcella** [stefano/pyduktape#6]
Hi,

We are considering the use of pyduktape for our commercial product but its licensing terms are not very clear, inside this repository we can't find any `LICENSE` file or Copyright notice for `pyduktape.pyx`, while the PYPI page [1] lists the package with a GPLv2 license:

```
License: GNU General Public License v2 (GPLv2) (GPL)
Author: Stefano Dissegna
```

Is GPLv2 the actual license?
Eventually, would you consider re-licensing pyduktape under a more commercial-friendly license like BSD, MIT o LGPL?

We would like to use and contribuite back to it, but as its stands we can't.

Thanks
Michele

[1] https://pypi.org/project/pyduktape/

**Comment by stefano** [comment]
The license (GPLv2) is the one specified in the setup.py file, which admittedly is not a great place. I will be adding a more explicit LICENSE file.

I prefer to use the GPL license for projects developed in my free time. I'm giving something away for free, so it seems fair that changes to the library should be contributed back.

I'd be open to the LGPL to make it easier to contribute back changes to the library itself while being able to use it in commercial projects, but it's not very clear to me how "dynamic linking" would be interpreted in the context of Python.

**Comment by mcella** [comment]
> The license (GPLv2) is the one specified in the setup.py file, which admittedly is not a great place. I will be adding a more explicit LICENSE file.

Perfect.

> I prefer to use the GPL license for projects developed in my free time. I'm giving something away for free, so it seems fair that changes to the library should be contributed back.

I understand and share your point of view. We definitely plan to add some features to the library and plan to publish on github what we are doing. Whether to merge or not is going to be your call.

> I'd be open to the LGPL to make it easier to contribute back changes to the library itself while being able to use it in commercial projects, but it's not very clear to me how "dynamic linking" would be interpreted in the context of Python.

You are perfectly right: “dynamic linking” is not clear in the context of Python. It could be argued that Python “runtime import” is equivalent to C “dynamic linking”. On the other and it would be difficult to justify a fair use of a GPL python module in a closed source project.

So I agree that the situation is not clear but if you are willing to consider fair the usage of your module in a closed source project than using LGPL expresses this intention more effectively.

Thanks for your time!
